server:
  port: 8868
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - application/json
      - application/xml
      - application/xhtml+xml
      - text/html
      - text/xml
      - text/plain
management:
  context-path: /admin
project:
  info:
    contact: meidongxu@baidu.com
    version: 0.0.1
    department: oped
    description: Gateway application of meu.
  uuap:
    app-service-home: http://172.21.199.1:8868/
    cas-service-url: http://172.21.199.1:8868/login
    cas-url-prefix: http://itebeta.baidu.com:8100/
    cas-url-login: http://itebeta.baidu.com:8100/login
    cas-url-logout: http://itebeta.baidu.com:8100/logout
  user-project-info: http://hz01-noah-yanzhijie1.hz01.baidu.com:8858/v1/users
#  user-project-info: http://localhost:8868/users
#  conf-man-url: http://hz01-noah-yanzhijie2.hz01.baidu.com:8878
  conf-man-url: http://localhost:8878
  service-man-url: http://hz01-noah-yanzhijie1.hz01.baidu.com:8858
#  policy-status-url: http://hz01-noah-yanzhijie2.hz01.baidu.com:8848
  policy-status-url: http://cq01-oda1.epc.baidu.com:8848
#  incident-url: http://hz01-noah-yanzhijie2.hz01.baidu.com:8848
  incident-url: http://cq01-oda1.epc.baidu.com:8848

  data-service-url: http://hz01-noah-yanzhijie1.hz01.baidu.com:8807


  cors: #By default CORS are not enabled. Uncomment to enable.
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800
  home-page: http://172.21.207.67:8888/?ed=1#/app/index

custom:
  boot:
    i18n:
      enabled: true
    trace:
      enabled: true
    spring:
      fox:
        enabled: true
        patterns:
          - /api/**
        api-info:
          title: meu-gateway
    access-log:
      enabled: true
spring:
  redis:
    host: localhost
#    password:
    port: 6379
    timeout: 1000
  aop:
    proxy-target-class: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    serialization-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

feign:
  hystrix:
    enabled: false
zuul:
  retryable: true
  add-proxy-headers: true
  RibbonRoutingFilter:
    post:
      diable: true
  routes:
    # alert configs
    alert-policy-status:
      id: alert-policy-status
      path: /api/v1/products/*/apps/*/policies/*/status/**
      url: ${project.policy-status-url}/v1/products
    alert-policy-block-status:
      id: alert-policy-block-status
      path: /api/v1/products/*/apps/*/policies/*/blockStatus/**
      url: ${project.policy-status-url}/v1/products
    alert-policy-block:
      id: alert-policy-block
      path: /api/v1/products/*/apps/*/policies/*/block/**
      url: ${project.policy-status-url}/v1/products
    alert-policy-unblock:
      id: alert-policy-unblock
      path: /api/v1/products/*/apps/*/policies/*/unblock/**
      url: ${project.policy-status-url}/v1/products
    alert-incident:
      id: alert-incident
      path: /api/v1/products/*/apps/*/incidents/**
      url: ${project.incident-url}/v1/products

    # data configs
    data-service-metric-meta:
      id: data-service-metric-meta
      path: /api/v1/products/*/namespaces/*/metrics/*/_meta/**
      url: ${project.data-service-url}/v1/products
    data-service-namespace-meta:
      id: data-service-namespace-meta
      path: /api/v1/products/*/namespaces/*/_meta/**
      url: ${project.data-service-url}/v1/products
    data-service-product-meta:
      id: data-service-product-meta
      path: /api/v1/products/*/_meta/**
      url: ${project.data-service-url}/v1/products
    data-service-data:
      id: data-service-data
      path: /api/v1/products/*/namespaces/*/metrics/*/_ts/**
      url: ${project.data-service-url}/v1/products

#    # config configs
#    conf-groups:
#      id: conf-groups
#      path: /api/v1/products/*/groups/**
#      url: ${project.conf-man-url}/v1/products
#    conf-callbacks:
#      id: conf-callbacks
#      path: /api/v1/products/*/callbacks/**
#      url: ${project.conf-man-url}/v1/products
#    conf-aggrTasks:
#      id: conf-aggrTasks
#      path: /api/v1/products/*/apps/*/aggrTasks/**
#      url: ${project.conf-man-url}/v1/products
#    conf-actions:
#      id: conf-actions
#      path: /api/v1/products/*/apps/*/actions/**
#      url: ${project.conf-man-url}/v1/products
#    conf-policies:
#      id: conf-policies
#      path: /api/v1/products/*/apps/*/policies/**
#      url: ${project.conf-man-url}/v1/products
#    conf-auditHistories:
#      id: conf-auditHistories
#      path: /api/v1/products/*/apps/*/auditHistories/**
#      url: ${project.conf-man-url}/v1/products
#    conf-derivedTasks:
#      id: conf-derivedTasks
#      path: /api/v1/products/*/apps/*/derivedTasks/**
#      url: ${project.conf-man-url}/v1/products
#    conf-execCollectTasks:
#      id: conf-execCollectTasks
#      path: /api/v1/products/*/apps/*/execCollectTasks/**
#      url: ${project.conf-man-url}/v1/products
#    conf-logCollectTasks:
#      id: conf-logCollectTasks
#      path: /api/v1/products/*/apps/*/logCollectTasks/**
#      url: ${project.conf-man-url}/v1/products
#    conf-patrolCollectTasks:
#      id: conf-patrolCollectTasks
#      path: /api/v1/products/*/apps/*/patrolCollectTasks/**
#      url: ${project.conf-man-url}/v1/products
#    conf-processCollectTasks:
#      id: conf-processCollectTasks
#      path: /api/v1/products/*/apps/*/processCollectTasks/**
#      url: ${project.conf-man-url}/v1/products
#    conf-metrics:
#      id: conf-metrics
#      path: /api/v1/products/*/apps/*/metrics/**
#      url: ${project.conf-man-url}/v1/products

    # service configs
#    service-users:
#      id: service-users
#      path: /api/v1/users/**
#      url: ${project.service-man-url}/v1/users
#    service-roles:
#      id: service-roles
#      path: /api/v1/roles/**
#      url: ${project.service-man-url}/v1/roles
#    service-products:
#      id: service-products
#      path: /api/v1/products/**
#      url: ${project.service-man-url}/v1/products
logging:
  level:
#    org.springframework.cloud: DEBUG
#    org.apache.commons.httpclient: DEBUG
    com.baidu.oped.iop.m4: DEBUG
    com.netflix: DEBUG
    feign: DEBUG


